### ISSUE TITLE
Unable to install using your Docker method. Also, if you could please clarify something.

### ISSUE THREAD

**Issue by Nostradamus1973** [n-thumann/IPTV-ReStream#216]
Good afternoon,

I came across your project and I think it will do what I need. Here's my scenario, I'm running a Virtual Machine in Linux Mint that's  already running a VPN, that VM is setup with a bridged Ethernet adapter, which allows me to connect up to separate instance NordVPN. I have the VM setup so I can access Italian (Rai) channels that are Geo Blocked. It's all working and tested, and it plays the Italian channels within that said VM
On my home network I have Jellyfin running on my LAN/WAN (on another linux box running Kubuntu) and I'm hoping that I can import the m3u from IPTV-ReStream and feed it into Jellyfin circumventing the Geo--Block.
Can your script do that?
I haven't been able to install it, otherwise I wouldn't have asked that question, but, before I go down that road I wanted some clarification. If I get some free time tomorrow I'll start working on a docker compose and see if I can get it up and rolling; I'm new to docker and use portainer for my docker instances, so, my docker-compose.yaml files take a LONG time. lol

Thank you for your help and time.
Have a nice day.

**Comment by Nostradamus1973** [comment]
Good morning,

Update:
So, I managed to get my docker-compose.yaml working. I can see it running on port 3000 within Portainer, but, that's about all the good news I have, on the flip side, I can't see anything on port 3000 and I have no idea why; I've tried changing the port without any luck to rule out confliction.

Here is what I have for a docker-compose.yaml file:

```
version: "3.1"
services:
  iptv-restream:
    container_name: iptv-restream
    environment:
      - TZ=America/New_York
    image: ghcr.io/n-thumann/iptv-restream:latest
    ports:
    # - 3030:3030    # Port used to stream
      - 3000:3000     # Web Interface Port
    # - 65001:65001   # HDHomeRun Port
    volumes:
      - /home/nostradamus/dockers/iptv-restream:/app/data/
    restart: unless-stopped
```
I revamped this from my github Cabernet docker compose, it uses HDhomerun. Would it be difficult to add this functionality?

Thx again.
